<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>me.hsgamer.bettergui</groupId>
        <artifactId>addon-parent</artifactId>
        <version>4.0</version>
    </parent>

    <artifactId>MaskedGUI</artifactId>
    <version>7.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>MaskedGUI</name>
    <description>Advanced GUI with Masks</description>

    <properties>
        <core.version>4.5.7</core.version>
        <craftux.version>1.6.3</craftux.version>
        <project.mainClass>me.hsgamer.bettergui.maskedgui.MaskedGUI</project.mainClass>
    </properties>

    <repositories>
        <repository>
            <id>codemc-public</id>
            <url>https://repo.codemc.io/repository/maven-public/</url>
        </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>2.43.0</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <java>
                        <includes>
                            <include>src/main/java/**/*.java</include>
                        </includes>
                        <licenseHeader>
                            <file>${basedir}/HEADER</file>
                        </licenseHeader>
                    </java>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <relocations>
                                <!-- HSCore License -->
                                <relocation>
                                    <pattern>me.hsgamer.hscore.license</pattern>
                                    <shadedPattern>${license.packageName}</shadedPattern>
                                </relocation>

                                <!-- HSCore -->
                                <relocation>
                                    <pattern>me.hsgamer.hscore</pattern>
                                    <shadedPattern>me.hsgamer.bettergui.lib.core</shadedPattern>
                                </relocation>

                                <!-- MineLib -->
                                <relocation>
                                    <pattern>io.github.projectunified.minelib</pattern>
                                    <shadedPattern>me.hsgamer.bettergui.lib.minelib</shadedPattern>
                                </relocation>

                                <!-- bStats -->
                                <relocation>
                                    <pattern>org.bstats</pattern>
                                    <shadedPattern>me.hsgamer.bettergui.lib.bstats</shadedPattern>
                                </relocation>

                                <!-- MapTemplate -->
                                <relocation>
                                    <pattern>io.github.projectunified.maptemplate</pattern>
                                    <shadedPattern>me.hsgamer.bettergui.maskedgui.lib.maptemplate</shadedPattern>
                                </relocation>

                                <!-- CraftUX -->
                                <relocation>
                                    <pattern>io.github.projectunified.craftux</pattern>
                                    <shadedPattern>me.hsgamer.bettergui.maskedgui.lib.craftux</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>me.hsgamer</groupId>
            <artifactId>hscore-license-spigotmc</artifactId>
            <version>${core.version}</version>
        </dependency>
        <dependency>
            <groupId>me.hsgamer</groupId>
            <artifactId>hscore-license-polymart</artifactId>
            <version>${core.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>me.hsgamer</groupId>
                    <artifactId>hscore-gson</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>me.hsgamer</groupId>
                    <artifactId>hscore-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.github.projectunified</groupId>
            <artifactId>map-template</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.projectunified</groupId>
            <artifactId>craftux-mask</artifactId>
            <version>${craftux.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>24.1.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
